### GET request to example server
GET http://localhost:10000

###

### POST request to example server
POST http://localhost:10000/api/patron-import/institution/1/toggle
Content-Type: application/json

{
  "enabled": true
}

###

#app.get('/api/patron-import/institution/:id/job/:job_id/failed-patrons', db.getFailedUsersByInstitutionId);
GET http://localhost:10000/api/patron-import/institution/14/job/68/failed-patrons


### GET institution metrics
GET http://localhost:10000/api/patron-import/institution/5/metrics


